title: Hello, world! Acá Felipe Riquelme
description: > # this means to ignore newlines until "baseurl:"
  Ingeniero en Negocios Internacionales entusiasta por el análisis de datos
  y machine learning 
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Felipe Riquelme Burgos # add your name
author-img: david-freeman.jpg # add your photo
about-author: Hola, ¿Qué tal? Soy un Ingeniero en Negocios Internacionales con experiencia en marketing, comercio exterior y desarrollo de negocios.
Apasionado por los datos y la historia que tienen que contar. # add description
social-github: feriq-burg # add your Github handle
social-linkedin: https://www.linkedin.com/in/felipe-alejandro-riquelme-burgos/ # add your Linkedin handle
social-email: feliperiquelme2499@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
