title: Hello, world! Acá Felipe Riquelme
description: > # this means to ignore newlines until "baseurl:"
  Ingeniero en Negocios Internacionales entusiasta por el análisis de datos
  y machine learning 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://feriq-burg.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author: Felipe Riquelme Burgos # add your name
author-img: felipe.jpg.png # add your photo
about-author: Hola, ¿Qué tal? Soy un Ingeniero en Negocios Internacionales entusiasta por los datos y la historia que tienen que contar.


social-cv: /assets/CV/CV_25_v2.pdf
social-github: feriq-burg # add your Github handle
social-linkedin: felipe-alejandro-riquelme-burgos/ # add your Linkedin handle
social-email: feliperiquelme2499@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
